version: '3.8'
services: 
  jupyter:
    build: courses
    image: courses:latest
    ports: 
      - '8888:8888'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./courses:/home/jovyan/work 